source:
  kind: timestamp_manifest
  manifest_path: ~/datasets/office_loop_1_train/rgb.txt
  dataset_root: ~/datasets/office_loop_1_train
  replay_realtime: true

orbslam:
  vocab_path: /home/sunches/vkr/ORB_SLAM3/Vocabulary/ORBvoc.txt
  settings_path: ~/datasets/office_loop_1_train/office_loop.yaml
use_viewer: false

runtime:
  live_view: false
  log_mode: fps_adaptive
  output_dir: ../runs/office_loop_1_train/{timestamp}
  ground_truth_path: /home/sunches/datasets/office_loop_1_train/true/GNSSPoses_tum.txt
  # max_frames: 200
